### ISSUE TITLE
Firmware 4.6.4_44

### ISSUE THREAD

**Issue by Epectase** [RobertSundling/neato-botvac#1]
Hello,

Before anything, just a big thank you for your amazing work !

I was wondering if firmware 4.6.4_44 can be listed ? Not tested personnally, have you any feedback about it ? It seems to be compatible at device level, not sure about Neato App if I read this reddit :
[https://www.reddit.com/r/NeatoRobotics/comments/13nngoz/vorwerk_vr300_firmware_on_neato_d3_d4_d5_d6_d7/](https://www.reddit.com/r/NeatoRobotics/comments/13nngoz/vorwerk_vr300_firmware_on_neato_d3_d4_d5_d6_d7/)

Firmaware available on Vorwek support page, unfortunatly the packaged is delivered with an expired certificate :
[https://support.vorwerk.com/hc/en-us/articles/360000796445-VR300-Robot-firmware-update-What-s-new](https://support.vorwerk.com/hc/en-us/articles/360000796445-VR300-Robot-firmware-update-What-s-new)

But I think it can be easily updated.

Best regards,
Pierre from France 👍

**Comment by RobertSundling** [comment]
I did notice that one, and I believe there are actually a couple of Vorwek versions newer than 4.6.0. From what I have read, however, all of the firmware versions of above 4.6.0 prevent the robots from connecting to the Neato Botvac app, which is why I didn't list them. But people may still have some use for them?
